--liquibase formatted sql

--changeset Gang:93
ALTER TABLE reminders
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일';

--changeset Gang:94
ALTER TABLE reminders
    ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일';